spring:
  boardsync:
    # Create an Atlassian (for Jira) API token here: https://id.atlassian.com/manage-profile/security/api-tokens
    # Then encode the following with base64: "{username}:{token}", e.g. here: https://www.base64encode.org/
    # Store the result in the environment variables.
    jira: ${JIRA_TOKEN}
    # Create a GitHub token here: https://github.com/settings/tokens/new
    # Then encode the following with base64: "{username}:{token}", e.g. here: https://www.base64encode.org/
    # Store the result in the environment variables.
    github: ${GITHUB_TOKEN}

server.error.include-stacktrace: on_trace_param

##Uncomment below to see wellformed sql logging with binded parameters
#spring.jpa.properties.hibernate.format_sql=true
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE


