server.error.include-stacktrace: on_trace_param

##Uncomment below to see wellformed sql logging with binded parameters
#spring.jpa.properties.hibernate.format_sql=true
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE


